### ISSUE TITLE
Not able to resolve paths

### ISSUE THREAD

**Issue by david-reir** [jprichardson/electron-mocha#107]
I was running 2 different commands:
electron-mocha --watch --ui tdd app/comunicator.service.int.js,
electron-mocha --watch --ui tdd app/**/*.int.js

On both cases I receive the error (on the second case I receive the error for app/**/*.int.js):
cannot resolve path (or pattern) 'app/comunicator.service.int.js'
Error: cannot resolve path (or pattern) 'app/comunicator.service.int.js'
    at Object.lookupFiles (/home/david/Workspace/catalog/node_modules/mocha/lib/utils.js:669:15)
    at args.files.forEach (/home/david/Workspace/catalog/node_modules/electron-mocha/mocha.js:33:32)
    at Array.forEach (native)
    at createFromArgs (/home/david/Workspace/catalog/node_modules/electron-mocha/mocha.js:32:14)
    at Object.run (/home/david/Workspace/catalog/node_modules/electron-mocha/mocha.js:60:17)
    at App.app.on (/home/david/Workspace/catalog/node_modules/electron-mocha/index.js:54:13)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

**Comment by inukshuk** [comment]
Are you sure those paths exist?

Side note, because I noticed you're using `--watch` in your example: electron-mocha [does not support](https://github.com/jprichardson/electron-mocha/issues/80) the option at all. There are plenty of good watchers for different platforms / situations available on NPM to do this.

**Comment by david-reir** [comment]
You were right, it worked. Thanks.
