### ISSUE TITLE
getPath undefined on Node Require in preload.js

### ISSUE THREAD

**Issue by yetyman** [jprichardson/electron-mocha#169]
Hello,

i am attempting to use Electron-mocha to run delayed mocha tests on the renderer process, loaded in preload
my package.json reads 
```    
"scripts": {
  "start": "electron .",
  "test": "electron-mocha -- --delay --preload --renderer"
},
```
my preload.js reads
```
//include testing packages
const Mocha = require('electron-mocha');
const assert = require('assert');
const electronPath = require('electron'); // Require Electron from the binaries included in node_modules.

const chai = require('chai');
const chaiAsPromised = require('chai-as-promised');


const MochaInstance = new Mocha();

function LoadTestCaseFiles() {
    var testDir = 'test';

    // Add each .js file to the mocha instance
    fs.readdirSync(testDir).filter(function (file) {
        // Only keep the .js files and not this file
        return file.substr(-3) === '.js' && file !== 'mocha.js';

    }).forEach(function (file) {
        MochaInstance.addFile(
            path.join(testDir, file)
        );
    });
};
LoadTestCaseFiles();

contextBridge.exposeInMainWorld(
    "test", {
        Mocha: Mocha,
        MochaInstance: MochaInstance,
        Run: run,
        Application: Application,
        assert: assert,
        electronPath:electronPath,
        chai: chai,
        chaiAsPromised: chaiAsPromised,
    }
);
```

And then I have a js function defined to be called at runtime in the renderer
```
function RunTests() {
    console.info("mocha run?");
    window.test.Run(function (failures) {
        process.exitCode = failures ? 1 : 0;  // exit with non-zero status if there were failures
    });
}
```

This fails right from the start as 
```
const Mocha = require('electron-mocha');
```

upon running `npm test`
The following error is thrown
```
electron/js2c/renderer_init.js:91 TypeError: Cannot read property 'getPath' of undefined
    at Object.<anonymous> (C:\Code\MyProject\MasterSolution\ElectronDisplay\node_modules\electron-mocha\lib\main.js:45:39)
    at Object.<anonymous> (C:\Code\MyProject\MasterSolution\ElectronDisplay\node_modules\electron-mocha\lib\main.js:67:3)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Code\MyProject\MasterSolution\ElectronDisplay\preload.js:17:15)
(anonymous) @ electron/js2c/renderer_init.js:91
```

Am I misunderstanding the uses of Electron-Mocha? is electron mocha already loaded in in my preload script via the preload directive? if so, what is the object called that I could access? Or is this what --require-main does?

**Comment by yetyman** [comment]
I've realized my misunderstanding. electron-mocha runs a new instance of chrome in which the mocha tests are executed for the convenience of chrome debug tools, this is awesome, I was under the impression it ran the mocha tests in the SAME renderer process as the app it is testing(hence why I didn't have Spectron referenced above.)
