### ISSUE TITLE
ELIFECYCLE with v0.35.2 on Travis CI

### ISSUE THREAD

**Issue by jviotti** [jprichardson/electron-mocha#28]
I'm suddenly getting this error with `electron-mocha` on Travis CI after upgrading my electron version to `v0.35.2`, which is not reproducible in OS X:

```sh
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.0.0/bin/node" "/home/travis/.nvm/versions/node/v4.0.0/bin/npm" "run-script" "test:main"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! herostratus@0.0.1 test:main: `electron-mocha --recursive tests/src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the herostratus@0.0.1 test:main script 'electron-mocha --recursive tests/src'.
npm ERR! This is most likely a problem with the herostratus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-mocha --recursive tests/src
npm ERR! You can get their info via:
npm ERR!     npm owner ls herostratus
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/resin-io/herostratus/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

https://travis-ci.org/resin-io/herostratus/jobs/93954044

I don't have a Linux machine to test at the moment, but maybe you encounter this error before, or have some insight about what could be causing it?

**Comment by jviotti** [comment]
The error is indeed gone by downgrading to an older electron version.

**Comment by jviotti** [comment]
The issue happens on both the main and renderer process.

**Comment by jviotti** [comment]
This issue seems to be related to https://github.com/atom/electron/issues/3666. I get the following error by executing my test suite in v0.35.2 in Ubuntu 14.04:

```sh
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to set path
    at Error (native)
    at Object.<anonymous> (/home/jviotti/Projects/herostratus/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/lib/init.js:120:7)
    at Object.<anonymous> (/home/jviotti/Projects/herostratus/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/lib/init.js:132:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:130:18)
    at node.js:982:3
```

**Comment by jprichardson** [comment]
Do you still get this issue with `electron-mocha@0.7.0` and electron `v0.36.0`?

**Comment by jviotti** [comment]
@jprichardson The issue is gone from by local Ubuntu 14.04 installation, but it persists on Travis CI:

```
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v0.12.9/bin/node" "/home/travis/.nvm/versions/node/v0.12.9/bin/npm" "run-script" "test:main"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! herostratus@0.0.1 test:main: `electron-mocha --recursive tests/src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the herostratus@0.0.1 test:main script 'electron-mocha --recursive tests/src'.
npm ERR! This is most likely a problem with the herostratus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-mocha --recursive tests/src
npm ERR! You can get their info via:
npm ERR!     npm owner ls herostratus
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/resin-io/herostratus/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by jviotti** [comment]
The issue is fixed by adding the following to my Travis CI configuration file, as recommended by the README (I missed it, sorry!):

```yml
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
``

**Comment by jprichardson** [comment]
I'm glad it's working for you!

**Comment by imlucas** [comment]
For folks coming across this in the future, https://www.npmjs.com/package/xvfb-maybe is great for this

**Comment by jprichardson** [comment]
@imlucas very cool! Would you be willing to submit a PR with a modification to the README with this?

**Comment by imlucas** [comment]
@jprichardson will do :+1:
