### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by black-snow** [jprichardson/electron-mocha#74]
Hi,

dunno if this actually is a electron-mocha issue. Suddenly I get an error:

> electron-mocha build --renderer

> Error encountered in ELECTRON_ASAR.js: Uncaught Error: Module version mismatch. Expected 49, got 48.
Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    ...

Sadly, I don't know what has changed since my last successful run. It suddenly stopped working.
I'm using electron-prebuilt 1.3.3.

**Comment by imlucas** [comment]
@black-snow https://github.com/electron/electron-rebuild should sort this out for you

**Comment by black-snow** [comment]
I got it figured out, thanks.
